services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apm_backend
    restart: always
    volumes:
      - ./backend/data:/app/data
    networks:
      - apm_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apm_frontend
    restart: always
    depends_on:
      - backend
    networks:
      - apm_network
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: apm_cloudflare_tunnel
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=
    networks:
      - apm_network
    depends_on:
      - frontend
      - backend

networks:
  apm_network:
    driver: bridge
